[Rainmeter]
Update=1000
;OnRefreshAction=[!RainmeterHideMeterGroup Hover]
;MouseOverAction=[!RainmeterShowMeterGroup Hover]
;MouseLeaveAction=[!RainmeterHideMeterGroup Hover]

[Metadata]
Name=Countdown
Config=
Description=An accurate countdown timer that will only show up when you hover over the icon.
Instructions=You can change the date in the countdown.ini file. | You can change the logo.png to match what you're counting down to.
Version=1.0
Tags=countdown | time
License=
Variant=1
Preview=#CURRENTPATH#preview.png

[Variables]
Color=255, 255, 255, 200
;FontName=Trebuchet MS
;FontHeight=32
FontName=We Are 26
FontHeight=28
;FontName=Ornitons-Serial
;FontHeight=28

;--- CONFIGURACIÓN DEL MUNDIAL 2026 ---;

toYear=2026
toMonth=6
toDay=11
toHour=15
toMinute=0
toSecond=0
ReleaseText="¡Arranca el Mundial!"

;Measures;

[MeasureScript]
Measure=script
ScriptFile=#CURRENTPATH#countdown.lua
TableName=Countdown
year=#toYear#
month=#toMonth#
day=#toDay#
hour=#toHour#
min=#toMinute#
sec=#toSecond#
fintext=#ReleaseText#

;Meters;

[MeterLogo]
Meter=Image
ImageName=logo.png
SolidColor=0,0,0,1
;X=R
X=(([MeterString:W] - [MeterLogo:W]) / 2)
Y=0
DynamicVariables=1

[MeterString]
Meter=string
MeasureName=MeasureScript
X=[MeterString:W]
Y=10R
H=100
FontFace=#FontName#
FontSize=#FontHeight#
FontColor=#Color#
StringStyle=BOLD
StringAlign=Right
AntiAlias=1
DynamicVariables=1
Text=%1
;Group=Hover